kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
    - containerPort: 3000
      hostPort: 3000
    - containerPort: 4000
      hostPort: 4000
    - containerPort: 5432
      hostPort: 5432
    - containerPort: 8545
      hostPort: 8545
    - containerPort: 30303
      hostPort: 30303
  extraMounts:
    - hostPath: /Users/leandrorichard/goProjects/src/github.com/ardanlabs/bets/zarf/ethereum
      containerPath: /ethereum