apiVersion: apps/v1
kind: Deployment
metadata:
  name: engine-api-pod
  namespace: engine-api-system
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: engine-api
  template:
    metadata:
      labels:
        app: engine-api
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      containers:
        # engine-api container configuration
        - name: engine-api
          resources:
            limits:
              cpu: "2000m" # Up to 2 full cores
            requests:
              cpu: "1000m" # Use 1 full cores